### ISSUE TITLE
libpd.so inside plugin bundle directory is not found by Ardour4

### ISSUE THREAD

**Issue by unknownError** [x37v/pdlv2#1]
while other hosts seem to find the bundles libpd.so file that comes with the plugin, ardour does not find it when trying to use a plugin. installing a system wide libpd.so in /usr/lib/libpd.so resolves the problem.

I don't know of this is related - but I ran into a problem like this when I was developing my plugin, see this thread for details. http://lists.lv2plug.in/htdig.cgi/devel-lv2plug.in/2012-February/000184.html

**Comment by x37v** [comment]
looks like I had libpd.so installed system wide, I'll move it and see what I can do to resolve this.

**Comment by x37v** [comment]
@unknownError should be resolved now. I was linking against libpd. When the host loaded the plugin it automatically tried to load the system wide shared library but we don't need this since I'm loading a different library from the plugin bundle directory.
